### ISSUE TITLE
Question about slow inference speed and math related benchamarks

### ISSUE THREAD

**Issue by Wilboludriver** [wjn1996/InstructGraph#14]
Dear author, 

Thanks for your amazing contributions. Could you please provide the rough running time of the evaluations? I used your inference script to evaluate on BBH, which is estimated to take more than 18 hours on one A100 (40GB). I want to make sure whether this is normal under your settings?

Meanwhile, the processing of math related benchmarks such as GSM8K, AQUA are not included in `/data/otherbenchmarks/`. Should I directly follow their orginal repo?

Thanks a lot for you reading and help!

Best

**Comment by wjn1996** [comment]
Dear Mr. Zhang

Thank you for taking the time to read our work. We apologize for the slow inference time, which is due to the fact that we haven't implemented the distribution yet. However, if you want to see approximate results, you can sample for BBH. 
For other benchmarks that are not available in the repository, you can download the original corpus directly and use the script to process the data. We will take time to add these processed data.

Best,
Authors

**Comment by Wilboludriver** [comment]
> Dear Mr. Zhang
> 
> Thank you for taking the time to read our work. We apologize for the slow inference time, which is due to the fact that we haven't implemented the distribution yet. However, if you want to see approximate results, you can sample for BBH. For other benchmarks that are not available in the repository, you can download the original corpus directly and use the script to process the data. We will take time to add these processed data.
> 
> Best, Authors
